AllCops:
  NewCops: enable
  Exclude:
    - "bin/bundle"

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
